//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_MarketItem
    {
        public int Id { get; set; }
        public string ItemName { get; set; }
        public string UserId { get; set; }
        public string ItemUrl { get; set; }
        public string AppId { get; set; }
        public Nullable<double> LastKnownPrice { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> ImageId { get; set; }
    
        public virtual App_Image App_Image { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
